site:
  title: Red Hat OpenShift Data Science
  start_page: rhods-book::index.adoc
content:
  sources:
  - url: ./
    branches: [main, 2.0]
ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui